kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: example-server
  namespace: mid-player
  labels:
    app: mid-player-example-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mid-player-example-server
    spec:
      containers:
      - name: mid-player-example-server
        image: divinomenezes/mid-player-example-server:0.0.1
        imagePullPolicy: Always
        env:
        - name: MIDDLEWARE_HOST
          value: broker.mid-player.svc.cluster.local
        - name: MIDDLEWARE_PORT
          value: "8080"
        ports:
        - name: broker
          containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 400M
